"""Initial migration with is_administrator field

Revision ID: 3449e6748a48
Revises: 
Create Date: 2026-01-07 17:42:58.208609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3449e6748a48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables in correct order (dependent tables first)
    op.drop_table('conversation_completion')
    op.drop_table('tag')
    op.drop_table('phrase')
    op.drop_table('conversation')
    op.drop_table('tag_type')

    # Add is_administrator column to users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_administrator', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_administrator')

    op.create_table('conversation',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('conversation_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('binary', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('reference_id', sa.VARCHAR(length=100), server_default=sa.text("'HSK1'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='conversation_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tag',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tag_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name_pinyin', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name_chinese', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tag_type_id'], ['tag_type.id'], name=op.f('tag_tag_type_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tag_pkey')),
    sa.UniqueConstraint('tag_type_id', 'name_pinyin', 'name_chinese', name=op.f('_tag_type_names_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('tag_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tag_type_pkey')),
    sa.UniqueConstraint('name', name=op.f('tag_type_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('phrase',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chinese', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chinese_question', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('chinese_response', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('phrase_pkey'))
    )
    op.create_table('conversation_completion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rendered_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('conversation_completion_conversation_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_completion_pkey'))
    )
    # ### end Alembic commands ###
