"""Add is_active field to User model

Revision ID: 894ea9546e76
Revises: 3449e6748a48
Create Date: 2026-01-07 18:05:06.648589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894ea9546e76'
down_revision = '3449e6748a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
